name: Crowdin Sync

on:
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Crowdin disabled for fork
        run: echo "Crowdin sync is disabled for this fork."
